RentalRestApi with all correction in models etc.
aflorczak/com.carflow.backend pull request #5
Opened 2023-03-14 15:08 UTC by aflorczak

Is everything alright?

2023-03-14 16:24 UTC, dawidowicz requested changes

2023-03-14 16:24 UTC, dawidowicz commented on src/main/java/com/carflow/backend/domains/rental/services/RentalService.java
> +    final private RentalStorage storage;
👍

2023-03-14 16:24 UTC, dawidowicz commented on src/main/java/com/carflow/backend/infrastructure/boundaries/in/api/v_0_0_1/rental/models/RentalDto.java
> +package com.carflow.backend.infrastructure.boundaries.in.api.v_0_0_1.rental.models;
singular form in names in packages, not plural

2023-03-15 09:58 UTC, aflorczak commented on src/main/java/com/carflow/backend/infrastructure/boundaries/out/rental/entity/RentalEntity.java
> +    private String orderId;
'Basic' attribute type should not be 'Persistence Entity'

2023-03-23 06:38 UTC, merged